### ISSUE TITLE
Allow the bulk loader to load very large files.

### ISSUE THREAD

**Issue by mildewey** [multinet-app/multinet-server#17]
The current limitation is a specified timeout in cherrypy.

**Comment by waxlamp** [comment]
Current plan is to use Girder Worker to create asynchronous bulk uploading jobs.

**Comment by waxlamp** [comment]
@AlmightyYakob, are we able to upload "very large files" without hitting a timeout now? Or do we also need "streaming uploaders" to complement the downloaders you're adding?

**Comment by AlmightyYakob** [comment]
I don't think there's anything in place to accommodate very large files as of yet. However, I'm not sure if/how flask supports this. I can look into this.

**Comment by waxlamp** [comment]
Thanks, @AlmightyYakob! My intuition tells me we should do whatever Girder does. Maybe "multipart upload" is the magic phrase?

**Comment by AlmightyYakob** [comment]
@gotdairyya Found an issue that I believe stems from this, so I'll bump this to higher priority. The specific issue she encountered was when uploading a D3 JSON file that is ~30MB (~800K lines), the upload would hang, ultimately timing out.

**Comment by AlmightyYakob** [comment]
I've been looking into this problem a bit, and it seems to come down to a few main things:

- We need to give the user a progress bar of the upload (already have this working locally)
- We need to either:
  - Remove the request timeout from `gunicorn` (easy), or:
  - Implement a chunking upload system (much more involved)


Regarding the second point, we may want to go with the first approach in the short-term. Implementing a chunking system would be much more involved, however would likely allow for more upload features (pausing/resuming is one example, which also helps with interrupted connections). However, this system also raises some questions, one being where to store chunks, since we don't really store raw data at the moment.

I looked into how Google Drive handles their uploads, and it looks like they just keep a connection open, like I'm proposing as a near-term approach.

**Comment by waxlamp** [comment]
> Regarding the second point, we may want to go with the first approach in the short-term.
> 

I agree, especially if the first approach is easy to execute, and double especially if it solves the particular problem that @gotdairyya uncovered.

> I looked into how Google Drive handles their uploads, and it looks like they just keep a connection open, like I'm proposing as a near-term approach.

More evidence that's it's a solid approach to a solution.

Does Drive keep an *HTTP* connection open, or does it use like websockers or something like that?

**Comment by AlmightyYakob** [comment]
> Does Drive keep an _HTTP_ connection open, or does it use like websockers or something like that?

It seems like it's keeping the HTTP `PUT` request open. I'm not sure how to tell if it's also using websockets or not, but from what I've seen online, websockets aren't really needed/beneficial for this.

**Comment by JackWilb** [comment]
I've applied a similar fix to another project, just keeping the connection open. It is a quick fix that gets around the immediate problem, but can lead to some strange behavior (e.g. you redeploy the app as an upload is happening breaking the upload). Once we stabilize the app and the deployment more, this could become a permanent fix, but we might see some bugs with our current deploy strategy in the mean time

**Comment by waxlamp** [comment]
> I've applied a similar fix to another project, just keeping the connection open. It is a quick fix that gets around the immediate problem, but can lead to some strange behavior (e.g. you redeploy the app as an upload is happening breaking the upload). Once we stabilize the app and the deployment more, this could become a permanent fix, but we might see some bugs with our current deploy strategy in the mean time

I'm not sure I understand. If you redeploy an app while an upload is active, wouldn't you expect it to break the upload? When you say "stabilize the app and deployment more", what do you mean?

**Comment by JackWilb** [comment]
You would expect it to break. I was trying to say that, since our app re-deploys each time a feature is merged, it could break uploads for users as we make new changes. When we stabilize deployments, by having releases that slowly make their way out, we can attempt to not break user uploads as they're happening

**Comment by waxlamp** [comment]
> You would expect it to break. I was trying to say that, since our app re-deploys each time a feature is merged, it could break uploads for users as we make new changes. When we stabilize deployments, by having releases that slowly make their way out, we can attempt to not break user uploads as they're happening

Ah, gotcha. I think the multi-part upload strategy @AlmightyYakob is cooking up may mitigate this risk.
