### ISSUE TITLE
Consider extracting `register_legacy_workspaces()` to an external script

### ISSUE THREAD

**Issue by waxlamp** [multinet-app/multinet-server#342]
Flask has database migration capability, which shows up as a Python command. I wonder if this would fall under that umbrella.

In general, if we changed the structure of the internal workspace names, I assume this sort of thing would be how we keep live servers kosher.

**Comment by AlmightyYakob** [comment]
I think the main concern here is when to run this script if we extract it. Since we're moving to heroku, we'd have to find a way to do this in their spin up process. Personally I don't think the way the function is being called is an issue, since it's only being called once when the server starts (which usually isn't too often), and most of the time isn't actually doing any migrating operations, just a check.

**Comment by waxlamp** [comment]
I agree with you on the operational details. However, this seems to be a classic case of database migration, which means we ought to at least learn the canonical way this would be done. I don't agree that we would need Heroku to do this; more likely it would be something we did to the Arango server directly. But I guess my main aim here is to figure out how things like `flask db migrate` work.
