### ISSUE TITLE
Allow specification of required network properties

### ISSUE THREAD

**Issue by AlmightyYakob** [multinet-app/multinet-server#397]
This is something I discovered when talking to @gotdairyya around a problem she was having importing data. She was trying to import an edge table that had the `_key` column, as well as the required `_from` and `_to` columns. Since we check if something is a node table first, it was seeing this and incorrectly inferring that it was a node table. For this specific issue, switching the order of these checks would probably be sufficient, but it demonstrates a larger point about our current data import mechanisms:

1. We currently don't have a way to specify the type of a table (node vs edge) when uploading a CSV file. This is supposed to be inferred by our backend, but we don't currently do a good job of that (as described above), and there could be residual edge cases there. I don't think it would be a bad idea to allow this.

2. We don't allow specifying the keys of the "source", "target", or "key" columns when uploading an edge table (or a graph). A decent amount of data shaping may be required for uploads to our backend to succeed.

I believe we have other issues that reference these same limitation, but the specific points I've laid out here seem like a good first step to address them, without dealing with too many edge cases. 

I'm curious to hear what @waxlamp and @JackWilb have to say regarding this. @gotdairyya if I represented the problem incorrectly, or there's things I've left out, please correct me.

**Comment by waxlamp** [comment]
To solve @gotdairyya's problem, let's immediately switch the order of the table type tests. I think this _is_ actually a long-term fix, since our model of what constitutes an edge table is simply that the table has a `_from` and a `_to` column. By our own definition, anything that doesn't match that criterion is a node table.

The other issues you raise are valid though. We could solve these in a few different ways. The least-resistance method is to rely on the upcoming AQL-based table feature to allow for free remixing of node tables into edge tables in-app.

On the other end of the spectrum, we could dispense with the distinction altogether, and let people pick any table at all to serve as an edge table, and perform the proper validation at that time. I don't like this solution because it will degrade the UX of creating a network.

In the middle is your (1) above: the user specifies at upload time if something is meant to be a node or edge table, and we do the proper validation on the spot. This is good in the same way that typeful programming is good: by forcing the user to specify their intent, we can catch errors in their data. However, this may degrade UX as well, since if we just had better logic in the backend, then things would work out just fine. (Consider that in almost 18 months of this project, we've had precisely one report of our table-type logic failing.)

I consider your (2) above to be somewhat orthogonal. It is an obvious feature to include, since we allow "key reshaping" on upload already. But we should keep in mind that obviously that won't solve all data shaping problems; in particular, someone may want an edge table with multiple from and to columns. Currently, IMO, the best way to handle this use case is through the upcoming AQL-based table feature.

My intuition on what to do here is to take the path of least resistance, at least for now: fix the logic error that we've uncovered. We should have a separate discussion on adding the "from/to" column selection option. But I don't think that enabling explicit control over table type will be worth the extra UI and backend work that it would take to implement it.

**Comment by JackWilb** [comment]
I agree with just moving the logic as a quick fix. 

Ultimately, if we choose to have a more verbose and configurable uploader with types (e.g. foreign keys, etc.), like Alex has suggested in the past, this will become less of an issue. It also solves the problem you mentioned, Roni, with having multiple foreign key columns. A user would then have to specify which columns they want to use as the key for the network they are creating.
